### ISSUE TITLE
Knife isn't changing.

### ISSUE THREAD

**Issue by Weeeishy** [Bara20/knifePlugin#1]
Hello,

I don't know if you support the plugin or not, but I just wanted to let you know that if a player has a knife from his inventory equipped then his knife won't change if he chooses a knife from the plugin's menu.

 In my case, I had a karambit, when I wanted to change my knife it didn't change. However, when I equipped the default knife from my inventory then I was able to change my knife using the plugin.

Not sure if thats intended or not though! 

Thanks

**Comment by Bara** [comment]
FollowCSGOServerGuidelines should be "no" in core.cfg

**Comment by Weeeishy** [comment]
It's already there mate, I've been using Franc's plugin so I didn't have issues with that. You might wanna try to re-produce the things I mentioned above to understand what I meant.

Thanks for your time anyways.
